import { AttendanceProcedure, AttendanceProcedureStatus } from "@/src/types/attendance_procedure";
import { ColumnDefinition } from "./patient";
import { i18n } from "@/src/lib/i18n";

export const ATTENDANCE_PROCEDURE_COLUMNS: ColumnDefinition<AttendanceProcedure>[] = [
  {
    name: "procedure_id",
    label: i18n.t("models.attendance_procedure.procedure"),
    type: "search_input",
    width: "100",
    required: true,
    grid: true,
    form: true,
    details: true,
    render: (item) => item.procedure?.name || "—",
  },
  {
    name: "status",
    label: i18n.t("models.attendance_procedure.status"),
    type: "select",
    width: "50",
    required: true,
    options: Object.values(AttendanceProcedureStatus).map((s) => ({
      label: i18n.t(`enums.procedure_status.${s.toLowerCase()}`),
      value: s
    })),
    grid: true,
    form: true,
    details: true,
    badge: true,
  },
  {
    name: "description",
    label: i18n.t("models.procedure.description"),
    type: "textarea",
    width: "100",
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "start_time",
    label: i18n.t("models.attendance_procedure.start_time"),
    type: "date",
    width: "50",
    grid: true,
    form: true,
    details: true,
    render: (item) => item.start_time ? new Date(item.start_time).toLocaleString() : "—",
  },
  {
    name: "end_time",
    label: i18n.t("models.attendance_procedure.end_time"),
    type: "date",
    width: "50",
    grid: true,
    form: true,
    details: true,
    render: (item) => item.end_time ? new Date(item.end_time).toLocaleString() : "—",
  },
  {
    name: "ordered_by_id",
    label: i18n.t("models.attendance_procedure.ordered_by"),
    type: "search_input",
    width: "50",
    grid: false,
    form: true,
    details: true,
    render: (item) => item.ordered_by?.full_name || "—",
  },
  {
    name: "executed_by_id",
    label: i18n.t("models.attendance_procedure.executed_by"),
    type: "search_input",
    width: "50",
    grid: true,
    form: true,
    details: true,
    render: (item) => item.executed_by?.full_name || "—",
  },
  {
    name: "medications",
    label: i18n.t("models.attendance_procedure.medications"),
    type: "multi_search_input",
    width: "100",
    grid: false,
    form: true,
    details: true,
    render: (item) => item.medications?.map(m => m.trade_name).join(", ") || "—",
  },
];
