import { Sex } from "@/src/types/patient";
import { EmploymentType, Employee } from "@/src/types/employee";
import { ColumnDefinition } from "./patient";
import { i18n } from "@/src/lib/i18n";

export const EMPLOYEE_COLUMNS: ColumnDefinition<Employee>[] = [
  {
    name: "full_name",
    label: i18n.t("models.employee.full_name"),
    type: "text",
    width: "100",
    required: true,
    placeholder: i18n.t("models.employee.full_name"),
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "social_name",
    label: i18n.t("models.employee.social_name"),
    type: "text",
    width: "100",
    placeholder: i18n.t("models.employee.social_name"),
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "cpf",
    label: i18n.t("models.employee.cpf"),
    type: "text",
    width: "50",
    required: true,
    placeholder: "000.000.000-00",
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "rg",
    label: i18n.t("models.employee.rg"),
    type: "text",
    width: "50",
    placeholder: i18n.t("models.employee.rg"),
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "birth_date",
    label: i18n.t("models.employee.birth_date"),
    type: "date",
    width: "50",
    required: true,
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "sex",
    label: i18n.t("models.employee.sex"),
    type: "select",
    width: "50",
    options: Object.values(Sex).map((s) => ({
      label: i18n.t(`enums.sex.${s.toLowerCase()}`),
      value: s,
    })),
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "marital_status",
    label: i18n.t("models.employee.marital_status"),
    type: "text",
    width: "50",
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "nationality",
    label: i18n.t("models.employee.nationality"),
    type: "text",
    width: "50",
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "phone",
    label: i18n.t("models.employee.phone"),
    type: "tel",
    width: "50",
    placeholder: "(00) 00000-0000",
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "hire_date",
    label: i18n.t("models.employee.hire_date"),
    type: "date",
    width: "50",
    required: true,
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "termination_date",
    label: i18n.t("models.employee.termination_date"),
    type: "date",
    width: "50",
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "employment_type",
    label: i18n.t("models.employee.employment_type"),
    type: "select",
    width: "50",
    options: Object.values(EmploymentType).map((s) => ({
      label: i18n.t(`enums.employment_type.${s.toLowerCase()}`),
      value: s,
    })),
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "salary",
    label: i18n.t("models.employee.salary"),
    type: "text",
    width: "50",
    placeholder: "0.00",
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "active",
    label: i18n.t("models.employee.active"),
    type: "select",
    width: "50",
    options: [
      { label: i18n.t("common.yes"), value: true as any },
      { label: i18n.t("common.no"), value: false as any },
    ],
    grid: true,
    form: true,
    details: true,
    badge: true,
  },
  {
    name: "role",
    label: i18n.t("models.employee.role"),
    type: "text",
    grid: true,
    form: false,
    details: true,
    render: (employee: Employee) => employee.role?.name || "—",
  },
  {
    name: "role_id",
    label: i18n.t("models.employee.role"),
    type: "select",
    width: "50",
    required: true,
    grid: false,
    form: true,
    details: false,
  },
];
