"""updating_attendance_enum

Revision ID: 0c0ae845bc80
Revises: 49cc4663ea29
Create Date: 2026-05-25 21:34:21.581146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c0ae845bc80'
down_revision = '49cc4663ea29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'status',
               existing_type=postgresql.ENUM('Waiting Triage', 'Waiting Consultation', 'Waiting Medication', 'Medical Return', 'Finished', 'Cancelled', name='attendancestatus'),
               type_=sa.Enum('waiting_triage', 'waiting_consultation', 'waiting_medication', 'medical_return', 'finished', 'cancelled', name='attendancestatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Waiting Triage'::attendancestatus"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'status',
               existing_type=sa.Enum('waiting_triage', 'waiting_consultation', 'waiting_medication', 'medical_return', 'finished', 'cancelled', name='attendancestatus', native_enum=False),
               type_=postgresql.ENUM('Waiting Triage', 'Waiting Consultation', 'Waiting Medication', 'Medical Return', 'Finished', 'Cancelled', name='attendancestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'Waiting Triage'::attendancestatus"))
    # ### end Alembic commands ###
