"""add access_level to roles

Revision ID: 118e9c2159fd
Revises: 340937750752
Create Date: 2026-05-26 02:53:41.780556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118e9c2159fd'
down_revision = '340937750752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('access_level', sa.Enum('admin', 'doctor', 'nurse', 'pharmaceutical', 'attendant', name='accesslevel', native_enum=False), server_default='attendant', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'access_level')
    # ### end Alembic commands ###
