"""updating_attendance_removing_useless_columns_adding_attendance_procedures_new_ones

Revision ID: 340937750752
Revises: 0c0ae845bc80
Create Date: 2026-05-25 23:11:34.110782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340937750752'
down_revision = '0c0ae845bc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_procedures', sa.Column('status', sa.Enum('pending', 'in_progress', 'done', 'canceled', name='attendanceprocedurestatus', native_enum=False), server_default='pending', nullable=False))
    op.add_column('attendance_procedures', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('attendances', sa.Column('gravity', sa.Enum('red', 'orange', 'yellow', 'green', 'blue', name='gravitylevel', native_enum=False), server_default='green', nullable=False))
    op.drop_column('attendances', 'status')
    op.drop_column('attendances', 'doctor_notes')
    op.drop_column('attendances', 'vitals_temp')
    op.drop_column('attendances', 'triage_notes')
    op.drop_column('attendances', 'vitals_bp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('vitals_bp', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('triage_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('vitals_temp', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('doctor_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'Waiting Triage'::attendancestatus"), autoincrement=False, nullable=False))
    op.drop_column('attendances', 'gravity')
    op.drop_column('attendance_procedures', 'description')
    op.drop_column('attendance_procedures', 'status')
    # ### end Alembic commands ###
