"""adding_new_columns_employees_table

Revision ID: 374a58599a3e
Revises: 90c0ce0554d8
Create Date: 2026-05-25 16:23:11.597119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '374a58599a3e'
down_revision = '90c0ce0554d8'
branch_labels = None
depends_on = None

employment_type_enum = postgresql.ENUM(
    'Full-time',
    'Part-time',
    'Contractor',
    'Temporary',
    name='employmenttype'
)

def upgrade():
    employment_type_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('social_name', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('rg', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=True))
    op.add_column('employees', sa.Column('marital_status', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('hire_date', sa.Date(), nullable=False))
    op.add_column('employees', sa.Column('termination_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('employment_type', sa.Enum('Full-time', 'Part-time', 'Contractor', 'Temporary', name='employmenttype'), server_default='Full-time', nullable=False))
    op.add_column('employees', sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('employees', sa.Column('active', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'active')
    op.drop_column('employees', 'salary')
    op.drop_column('employees', 'employment_type')
    op.drop_column('employees', 'termination_date')
    op.drop_column('employees', 'hire_date')
    op.drop_column('employees', 'phone')
    op.drop_column('employees', 'nationality')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'sex')
    op.drop_column('employees', 'rg')
    op.drop_column('employees', 'social_name')
    # ### end Alembic commands ###

    employment_type_enum.drop(op.get_bind())
