"""remove prescription and medical record tables

Revision ID: 75f15b440f65
Revises: 6a006d56d644
Create Date: 2026-05-27 22:17:46.383439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75f15b440f65'
down_revision = '6a006d56d644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_medical_records_id'), table_name='medical_records')
    op.drop_table('medical_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('MEDICATION', 'PROCEDURE', name='recordtype'), autoincrement=False, nullable=False),
    sa.Column('medication_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('procedure_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'cancelled', name='recordstatus'), server_default=sa.text("'pending'::recordstatus"), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('registration_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('medical_records_employee_id_fkey')),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('medical_records_medication_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medical_records_patient_id_fkey')),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name=op.f('medical_records_procedure_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_records_pkey'))
    )
    op.create_index(op.f('ix_medical_records_id'), 'medical_records', ['id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('attendance_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('medication_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_executed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], name=op.f('prescriptions_attendance_id_fkey')),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('prescriptions_medication_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prescriptions_pkey'))
    )
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    # ### end Alembic commands ###
