"""adding_new_columns_patients_med_records_and_timestamps

Revision ID: 90c0ce0554d8
Revises: dd1c28e47aa7
Create Date: 2026-05-25 14:15:19.925142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90c0ce0554d8'
down_revision = 'dd1c28e47aa7'
branch_labels = None
depends_on = None

record_status_enum = postgresql.ENUM(
    'pending',
    'completed',
    'cancelled',
    name='recordstatus'
)

sex_enum = postgresql.ENUM(
    'MALE',
    'FEMALE',
    'OTHER',
    name='sex'
)

blood_type_enum = postgresql.ENUM(
    'A+',
    'A-',
    'B+',
    'B-',
    'AB+',
    'AB-',
    'O+',
    'O-',
    name='bloodtype'
)

def upgrade():
    # Create ENUM types manually
    record_status_enum.create(op.get_bind())
    sex_enum.create(op.get_bind())
    blood_type_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('medical_records', sa.Column('status', record_status_enum, server_default='pending', nullable=False))
    op.add_column('medical_records', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('medical_records', sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('medical_records', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('medical_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('medications', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('medications', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('patients', sa.Column('social_name', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('rg', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('sex', sex_enum, nullable=True))
    op.add_column('patients', sa.Column('marital_status', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('mother_name', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('blood_type', blood_type_enum, nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('patients', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('procedures', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('procedures', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('procedures', 'updated_at')
    op.drop_column('procedures', 'created_at')
    op.alter_column('patients', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'created_at')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'blood_type')
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'mother_name')
    op.drop_column('patients', 'nationality')
    op.drop_column('patients', 'marital_status')
    op.drop_column('patients', 'sex')
    op.drop_column('patients', 'rg')
    op.drop_column('patients', 'social_name')
    op.drop_column('medications', 'updated_at')
    op.drop_column('medications', 'created_at')
    op.alter_column('medical_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('medical_records', 'updated_at')
    op.drop_column('medical_records', 'registration_date')
    op.drop_column('medical_records', 'active')
    op.drop_column('medical_records', 'status')
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    # ### end Alembic commands ###

    # Drop ENUM types manually
    blood_type_enum.drop(op.get_bind())
    sex_enum.drop(op.get_bind())
    record_status_enum.drop(op.get_bind())
