"""add_employees_table_updating_users_table

Revision ID: dd1c28e47aa7
Revises: 35db7a18e3b1
Create Date: 2026-05-24 03:19:42.214083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1c28e47aa7'
down_revision = '35db7a18e3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_cpf'), 'employees', ['cpf'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.add_column('medical_records', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('medical_records_user_id_fkey'), 'medical_records', type_='foreignkey')
    op.create_foreign_key(None, 'medical_records', 'employees', ['employee_id'], ['id'])
    op.drop_column('medical_records', 'user_id')
    op.add_column('users', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['employee_id'])
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'])
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'employee_id')
    op.add_column('medical_records', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.create_foreign_key(op.f('medical_records_user_id_fkey'), 'medical_records', 'users', ['user_id'], ['id'])
    op.drop_column('medical_records', 'employee_id')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_cpf'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
